const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"求职意向管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"企业类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQiye"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"招聘岗位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhaopin"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"企业管理",
                        "menuJump":"列表",
                        "tableName":"qiye"
                    }
                ],
                "menu":"企业管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学校人员管理",
                        "menuJump":"列表",
                        "tableName":"xuexiaorenyuan"
                    }
                ],
                "menu":"学校人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "导入导出",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"简历管理",
                        "menuJump":"列表",
                        "tableName":"jianli"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职位招聘管理",
                        "menuJump":"列表",
                        "tableName":"zhaopin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"职位留言管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"职位收藏管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinCollection"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"简历投递管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinToudi"
                    }
                ],
                "menu":"职位招聘管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户咨询管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinChat"
                    }
                ],
                "menu":"用户咨询管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职位招聘管理",
                        "menuJump":"列表",
                        "tableName":"zhaopin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"职位留言管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinLiuyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"简历投递管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinToudi"
                    }
                ],
                "menu":"职位招聘管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"用户咨询管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinChat"
                    }
                ],
                "menu":"用户咨询管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"企业",
        "tableName":"qiye"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"企业管理",
                        "menuJump":"列表",
                        "tableName":"qiye"
                    }
                ],
                "menu":"企业管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "导入导出",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"简历管理",
                        "menuJump":"列表",
                        "tableName":"jianli"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "审核"
                        ],
                        "menu":"职位招聘管理",
                        "menuJump":"列表",
                        "tableName":"zhaopin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"职位留言管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinLiuyan"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"简历投递管理",
                        "menuJump":"列表",
                        "tableName":"zhaopinToudi"
                    }
                ],
                "menu":"职位招聘管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"学校人员",
        "tableName":"xuexiaorenyuan"
    }
]
    }
}
export default menu;
